CREATE DATABASE IF NOT EXISTS peli;
USE peli;
CREATE TABLE hahmo (
    charID INT UNSIGNED AUTO_INCREMENT,
    posX SMALLINT,
    posY SMALLINT,
    PRIMARY KEY (charID)
);

CREATE TABLE vihollinen (
    eID INT UNSIGNED AUTO_INCREMENT,
    hp SMALLINT UNSIGNED,
    posX SMALLINT,
    posY SMALLINT,
)
